@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US001



class Client {
String name
 int passportNumber
  int phoneNumber
  int taxNumber
   String address
    String email
}
Unregistered\nUser  "1" -- Client : registers into >
@enduml